name: Export Clean Project

on:
  push:
    branches:
      - main

jobs:
  export-clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Clean ZIP
        run: |
          zip -r RogueShooter.zip . \
            -x "**/Library/**" \
            -x "**/Temp/**" \
            -x "**/Build/**" \
            -x "**/Logs/**" \
            -x "**/obj/**" \
            -x "**/.git/**" \
            -x "**/.vscode/**" \
            -x "**/.github/**" \
            -x "**/*.zip"

