name: Export Clean Project

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  export-clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Clean ZIP (Only Scripts and Docs)
        run: |
          mkdir CleanExport
          cp -r Assets/Scripts CleanExport/Scripts
          cp -r Dokumentaatio CleanExport/Dokumentaatio
          cd CleanExport
          zip -r ../RogueShooter.zip .
          cd ..

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Clean Export ${{ github.run_number }}
          tag_name: clean-export-${{ github.run_number }}
          files: RogueShooter.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



