name: Generate Doxygen Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Clean old documentation
        run: rm -rf Dokumentaatio/html

      - name: Generate Doxygen documentation
        run: doxygen Dokumentaatio/Doxyfile

      - name: List generated HTML files
        run: ls -R Dokumentaatio/html || echo "No files generated"

      - name: Upload Doxygen HTML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: Dokumentaatio/html
