name: Generate Doxygen Docs

on:
  push:
    branches:
      - main  # tai mikä tahansa haara johon haluat sidoksen

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz

      - name: Generate Doxygen documentation
        run: doxygen Dokumentaatio/Doxyfile

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: Dokumentaatio/html